services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./Data_process/chroma_db:/app/Data_process/chroma_db

  redis:
    image: redis/redis-stack:7.4.0-v8
    # TODO 在正式部署的时候，要改端口暴露
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30m
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:18-bookworm
    # TODO 在正式部署的时候，要改端口暴露
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agent
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent_password
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent -d agent"]
      interval: 30m
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data:
  postgres_data: